[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "grief"
description = "A highly customisable Discord bot"
readme = "README.md"
authors = [{ name = "sin -- <damon@slit.sh>" }]

[project.scripts]
grief = "grief.__main__:main"
grief-setup = "grief.setup:run_cli"

[tool.black]
line-length = 99
required-version = '23'
target-version = ['py38']
include = '\.py$'
force-exclude = '''
/(
    grief\/vendored
)/
'''
