[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
authors     = ["sin <damon@slit.sh>"]
description = "a premium discord bot"
license     = "MIT  "
name        = "grief"
version     = "1.3.2"
dynamic = ["version", "requires-python", "dependencies", "optional-dependencies"]

[project.scripts]
grief = "grief.__main__:main"
grief-setup = "grief.setup:run_cli"

[project.entry-points.pytest11]
grief-discordbot = "grief.pytest"

[tool.black]
line-length = 99
required-version = '23'
target-version = ['py38']
include = '\.py$'
force-exclude = '''
/(
    grief\/vendored
)/
'''

[tool.pytest.ini_options]
asyncio_mode = 'auto'