[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "grief"
description = "A highly customisable Discord bot"
readme = "README.md"
authors = [{ name = "sin -- <damon@slit.sh>" }]
classifiers = [
    "Development Status :: 5 - Production",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dynamic = ["version", "requires-python", "dependencies", "optional-dependencies"]

[project.scripts]
grief = "grief.__main__:main"
grief-setup = "grief.setup:run_cli"

[project.entry-points.pytest11]
grief-discordbot = "grief.pytest"

[tool.black]
line-length = 99
required-version = '23'
target-version = ['py38']
include = '\.py$'
force-exclude = '''
/(
    grief\/vendored
)/
'''

[tool.pytest.ini_options]
asyncio_mode = 'auto'

[tool.dependencies]
aiodns==3.0.0
aiohttp==3.8.5
aiohttp-json-rpc
discord-py
red-lavalink
aiohttp-json-rpc==0.13.3
aiosignal==1.3.1
apsw==3.42.0.1
async-timeout==4.0.3
attrs==23.1.0
babel==2.12.1
brotli==1.0.9
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
contextlib2==21.6.0
discord-py==2.3.2
frozenlist==1.4.0
idna==3.4
importlib-metadata==6.8.0
markdown==3.4.4
markdown-it-py==3.0.0
mdurl==0.1.2
multidict==6.0.4
orjson==3.9.4
packaging==23.1
platformdirs==3.10.0
psutil==5.9.5
pycares==4.3.0
pycparser==2.21
pygments==2.16.1
python-dateutil==2.8.2
pytz==2023.3
pyyaml==6.0.1
rapidfuzz==3.2.0
red-commons==1.0.0
red-lavalink==0.11.0
rich==13.5.2
schema==0.7.5
six==1.16.0
typing-extensions==4.7.1
yarl==1.9.2
zipp==3.16.2
colorama==0.4.6; sys_platform == "win32"
distro==1.8.0; sys_platform == "linux" and sys_platform == "linux"
uvloop==0.17.0; (sys_platform != "win32" and platform_python_implementation == "CPython") and sys_platform != "win32"